import A from '../images/drop-caps/a.jpg';
import B from '../images/drop-caps/b.jpg';
import C from '../images/drop-caps/c.jpg';
import D from '../images/drop-caps/d.jpg';
import E from '../images/drop-caps/e.jpg';
import F from '../images/drop-caps/f.jpg';
import G from '../images/drop-caps/g.jpg';
import H from '../images/drop-caps/h.jpg';
import I from '../images/drop-caps/i.jpg';
import J from '../images/drop-caps/j.jpg';
import K from '../images/drop-caps/k.jpg';
import L from '../images/drop-caps/l.jpg';
import M from '../images/drop-caps/m.jpg';
import N from '../images/drop-caps/n.jpg';
import O from '../images/drop-caps/o.jpg';
import P from '../images/drop-caps/p.jpg';
import Q from '../images/drop-caps/q.jpg';
import R from '../images/drop-caps/r.jpg';
import S from '../images/drop-caps/s.jpg';
import T from '../images/drop-caps/t.jpg';
import U from '../images/drop-caps/u.jpg';
import V from '../images/drop-caps/v.jpg';
import W from '../images/drop-caps/w.jpg';
import Y from '../images/drop-caps/y.jpg';
import Z from '../images/drop-caps/z.jpg';

export default { A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, Y, Z };
